from enum import Enum
from dataclasses import dataclass


@dataclass
class ProvinceData:
    code: int
    name_en: str
    name_th: str


class Province(Enum):
    BANGKOK = ProvinceData(10, "Bangkok", "กรุงเทพมหานคร")
    SAMUT_PRAKAN = ProvinceData(11, "Samut Prakan", "สมุทรปราการ")
    NONTHABURI = ProvinceData(12, "Nonthaburi", "นนทบุรี")
    PATHUM_THANI = ProvinceData(13, "Pathum Thani", "ปทุมธานี")
    PHRA_NAKHON_SI_AYUTTHAYA = ProvinceData(14, "Phra Nakhon Si Ayutthaya", "พระนครศรีอยุธยา")
    ANG_THONG = ProvinceData(15, "Ang Thong", "อ่างทอง")
    LOBURI = ProvinceData(16, "Loburi", "ลพบุรี")
    SING_BURI = ProvinceData(17, "Sing Buri", "สิงห์บุรี")
    CHAI_NAT = ProvinceData(18, "Chai Nat", "ชัยนาท")
    SARABURI = ProvinceData(19, "Saraburi", "สระบุรี")
    CHON_BURI = ProvinceData(20, "Chon Buri", "ชลบุรี")
    RAYONG = ProvinceData(21, "Rayong", "ระยอง")
    CHANTHABURI = ProvinceData(22, "Chanthaburi", "จันทบุรี")
    TRAT = ProvinceData(23, "Trat", "ตราด")
    CHACHOENGSAO = ProvinceData(24, "Chachoengsao", "ฉะเชิงเทรา")
    PRACHIN_BURI = ProvinceData(25, "Prachin Buri", "ปราจีนบุรี")
    NAKHON_NAYOK = ProvinceData(26, "Nakhon Nayok", "นครนายก")
    SA_KAEO = ProvinceData(27, "Sa Kaeo", "สระแก้ว")
    NAKHON_RATCHASIMA = ProvinceData(30, "Nakhon Ratchasima", "นครราชสีมา")
    BURI_RAM = ProvinceData(31, "Buri Ram", "บุรีรัมย์")
    SURIN = ProvinceData(32, "Surin", "สุรินทร์")
    SI_SA_KET = ProvinceData(33, "Si Sa Ket", "ศรีสะเกษ")
    UBON_RATCHATHANI = ProvinceData(34, "Ubon Ratchathani", "อุบลราชธานี")
    YASOTHON = ProvinceData(35, "Yasothon", "ยโสธร")
    CHAIYAPHUM = ProvinceData(36, "Chaiyaphum", "ชัยภูมิ")
    AMNAT_CHAROEN = ProvinceData(37, "Amnat Charoen", "อำนาจเจริญ")
    BUENG_KAN = ProvinceData(38, "Bueng Kan", "บึงกาฬ")
    NONG_BUA_LAM_PHU = ProvinceData(39, "Nong Bua Lam Phu", "หนองบัวลำภู")
    KHON_KAEN = ProvinceData(40, "Khon Kaen", "ขอนแก่น")
    UDON_THANI = ProvinceData(41, "Udon Thani", "อุดรธานี")
    LOEI = ProvinceData(42, "Loei", "เลย")
    NONG_KHAI = ProvinceData(43, "Nong Khai", "หนองคาย")
    MAHA_SARAKHAM = ProvinceData(44, "Maha Sarakham", "มหาสารคาม")
    ROI_ET = ProvinceData(45, "Roi Et", "ร้อยเอ็ด")
    KALASIN = ProvinceData(46, "Kalasin", "กาฬสินธุ์")
    SAKON_NAKHON = ProvinceData(47, "Sakon Nakhon", "สกลนคร")
    NAKHON_PHANOM = ProvinceData(48, "Nakhon Phanom", "นครพนม")
    MUKDAHAN = ProvinceData(49, "Mukdahan", "มุกดาหาร")
    CHIANG_MAI = ProvinceData(50, "Chiang Mai", "เชียงใหม่")
    LAMPHUN = ProvinceData(51, "Lamphun", "ลำพูน")
    LAMPANG = ProvinceData(52, "Lampang", "ลำปาง")
    UTTARADIT = ProvinceData(53, "Uttaradit", "อุตรดิตถ์")
    PHRAE = ProvinceData(54, "Phrae", "แพร่")
    NAN = ProvinceData(55, "Nan", "น่าน")
    PHAYAO = ProvinceData(56, "Phayao", "พะเยา")
    CHIANG_RAI = ProvinceData(57, "Chiang Rai", "เชียงราย")
    MAE_HONG_SON = ProvinceData(58, "Mae Hong Son", "แม่ฮ่องสอน")
    NAKHON_SAWAN = ProvinceData(60, "Nakhon Sawan", "นครสวรรค์")
    UTHAI_THANI = ProvinceData(61, "Uthai Thani", "อุทัยธานี")
    KAMPHAENG_PHET = ProvinceData(62, "Kamphaeng Phet", "กำแพงเพชร")
    TAK = ProvinceData(63, "Tak", "ตาก")
    SUKHOTHAI = ProvinceData(64, "Sukhothai", "สุโขทัย")
    PHITSANULOK = ProvinceData(65, "Phitsanulok", "พิษณุโลก")
    PHICHIT = ProvinceData(66, "Phichit", "พิจิตร")
    PHETCHABUN = ProvinceData(67, "Phetchabun", "เพชรบูรณ์")
    RATCHABURI = ProvinceData(70, "Ratchaburi", "ราชบุรี")
    KANCHANABURI = ProvinceData(71, "Kanchanaburi", "กาญจนบุรี")
    SUPHAN_BURI = ProvinceData(72, "Suphan Buri", "สุพรรณบุรี")
    NAKHON_PATHOM = ProvinceData(73, "Nakhon Pathom", "นครปฐม")
    SAMUT_SAKHON = ProvinceData(74, "Samut Sakhon", "สมุทรสาคร")
    SAMUT_SONGKHRAM = ProvinceData(75, "Samut Songkhram", "สมุทรสงคราม")
    PHETCHABURI = ProvinceData(76, "Phetchaburi", "เพชรบุรี")
    PRACHUAP_KHIRI_KHAN = ProvinceData(77, "Prachuap Khiri Khan", "ประจวบคีรีขันธ์")
    NAKHON_SI_THAMMARAT = ProvinceData(80, "Nakhon Si Thammarat", "นครศรีธรรมราช")
    KRABI = ProvinceData(81, "Krabi", "กระบี่")
    PHANGNGA = ProvinceData(82, "Phangnga", "พังงา")
    PHUKET = ProvinceData(83, "Phuket", "ภูเก็ต")
    SURAT_THANI = ProvinceData(84, "Surat Thani", "สุราษฎร์ธานี")
    RANONG = ProvinceData(85, "Ranong", "ระนอง")
    CHUMPHON = ProvinceData(86, "Chumphon", "ชุมพร")
    SONGKHLA = ProvinceData(90, "Songkhla", "สงขลา")
    SATUN = ProvinceData(91, "Satun", "สตูล")
    TRANG = ProvinceData(92, "Trang", "ตรัง")
    PHATTHALUNG = ProvinceData(93, "Phatthalung", "พัทลุง")
    PATTANI = ProvinceData(94, "Pattani", "ปัตตานี")
    YALA = ProvinceData(95, "Yala", "ยะลา")
    NARATHIWAT = ProvinceData(96, "Narathiwat", "นราธิวาส")
